---
title: "baipishu"
author: "marshall ma"
date: "7/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r tools, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(data.table)
library(naniar)
library(stringr)
library(maps)
library(mapdata)
library(arsenal)
```



```{r import, include=FALSE}
data <- read.csv("~/Documents/2020_2Summer/research/0Yale2009/data/output/bps_df0722_xm0722.csv", comment.char="#", encoding = "UTF-8")

head(data)

summary(data$PSS_sum)
```


#Stage I: Filtering
- we still need to work on the inclusion/exclusion criteria
- ignore at this moment
时间低于10分钟。
PSS: 所有题目得分一致。
PHQ第10题和前9题逻辑不一致。
没有使用心理咨询等服务却选了满意度（没有选“不适用”）。
```{r filter, include=FALSE}

#look at distribution of time complete
#x <- data[which(data$TimeComplete < 2000),]
#ggplot(x, aes(x = TimeComplete)) + geom_histogram(bins = 40)+ geom_vline(xintercept = 600)


check <- data %>%
  mutate(
    qc_idx = 0,
    #C2, time of 3SD
    qc_idx = ifelse(PHQ_sum == 0 & PHQ10 != 999, qc_idx + 1, qc_idx),
    qc_idx = ifelse(PHQ_sum > 0 & PHQ10 == 999, qc_idx + 1, qc_idx)
    #C5 age match
    #6 29.7 (QLES2) high should correspond to -> 28b1-6 low
    #7 29.8 (QLES3) high should correspond to -> 29.1-5 high
    #8 29.8 (QLES3) high should correspond to -> 29.6-7 medium to high
         )

vis_miss(data)

```


```{r transformation}
data_vis <- data %>% 
  mutate(age_grp = ifelse(Age >= 25, "25+", "below25"), 
         gender_grp = ifelse(Gender == 1, "Male", 
                      ifelse(Gender == 2, "Female", 
                      ifelse(Gender < 667, "Spectrum", NA))), 
         degree_grp = ifelse(Degree == 1, "本科", 
                      ifelse(Degree == 2, "硕士", 
                      ifelse(Degree == 3, "MBA", 
                      ifelse(Degree == 4, "博士", NA)))),
         religion_grp = ifelse(Religion %in% c(1,2,3,4,5), "教", 
                      ifelse(Religion == 6, "无宗教信仰", NA)),
         gpa_grp = ifelse(GPA == 1, "a.3.8+", 
                      ifelse(GPA == 2, "b.3.5-3.8", 
                      ifelse(GPA == 3, "c.3.3-3.5", 
                      ifelse(GPA == 4, "d.3.0-3.3", 
                      ifelse(GPA == 5, "e.3-", NA))))),
         gpa_change_grp = ifelse(GradeChange == 1, "a明显变好", 
                      ifelse(GradeChange == 2, "b变好", 
                      ifelse(GradeChange == 3, "c不变", 
                      ifelse(GradeChange == 4, "d变差", 
                      ifelse(GradeChange == 5, "e明显变差", NA))))),
        )


```

```{r visulization}

#need to summarize data first to get error bar
hist(data_vis$PSS_sum)


#gather and spread 
#, color = gender_grp
data_vis_pwb <- data_vis %>%
  gather(PWB, PWB_val, PSS_sum:QLES_sum)

head(data_vis_pwb)

ggplot(data_vis_pwb, aes(x = PWB, y = PWB_val, fill = as.factor(gpa_grp))) + geom_bar(position = "dodge", stat = "summary", fun = mean) + scale_fill_brewer(palette="Set3")



data_vis_lt <- data_vis %>%
  gather(Latent, Lt_val, c(ERQ_reap:MEMS, SSSI_avg))


ggplot(data_vis_lt, aes(x = Latent, y = Lt_val, fill = gpa_grp)) + geom_bar(stat="summary", position = "dodge", fun = mean) + scale_fill_brewer(palette="Set3")


```


```{r summary}


#WARNING
#Still need to provide input parameters such as what test to use and what stats to display

#Part 0, summary stats PWB
table_01 <- tableby(age_grp ~ PHQ_sum + GAD_sum + PSS_sum + SWLS_sum + QLES_sum + SCOFF_nervosa, data = data_vis)
summary(table_01, title = "PWB By Age", text = TRUE)


table_02 <- tableby(gender_grp ~ PHQ_sum + GAD_sum + PSS_sum + SWLS_sum + QLES_sum + SCOFF_nervosa, data = data_vis)
summary(table_02, title = "PWB By Gender", text = TRUE)


table_03 <- tableby(degree_grp ~ PHQ_sum + GAD_sum + PSS_sum + SWLS_sum + QLES_sum + SCOFF_nervosa, data = data_vis)
summary(table_03, title = "PWB By Degree", text = TRUE)


table_04 <- tableby(religion_grp ~ PHQ_sum + GAD_sum + PSS_sum + SWLS_sum + QLES_sum + SCOFF_nervosa, data = data_vis)
summary(table_04, title = "PWB By Religion", text = TRUE)


table_05 <- tableby(gpa_grp ~ PHQ_sum + GAD_sum + PSS_sum + SWLS_sum + QLES_sum + SCOFF_nervosa, data = data_vis)
summary(table_05, title = "PWB By GPA", text = TRUE)


table_06 <- tableby(gpa_change_grp ~ PHQ_sum + GAD_sum + PSS_sum + SWLS_sum + QLES_sum + SCOFF_nervosa, data = data_vis)
summary(table_06, title = "PWB By GPA(change)", text = TRUE)


#-------------------------------------------------------
#Part 1, summary stats for latent
table_11 <- tableby(age_grp ~ ERQ_reap + ERQ_sup + GSE_sum + MEMS_sum + SSSI_avg, data = data_vis)
summary(table_11, title = "Latent By Age", text = TRUE)


table_12 <- tableby(gender_grp ~ ERQ_reap + ERQ_sup + GSE_sum + MEMS_sum + SSSI_avg, data = data_vis)
summary(table_12, title = "Latent By Gender", text = TRUE)


table_13 <- tableby(degree_grp ~ ERQ_reap + ERQ_sup + GSE_sum + MEMS_sum + SSSI_avg, data = data_vis)
summary(table_13, title = "Latent By Degree", text = TRUE)


table_14 <- tableby(religion_grp ~ ERQ_reap + ERQ_sup + GSE_sum + MEMS_sum + SSSI_avg, data = data_vis)
summary(table_14, title = "Latent By Religion", text = TRUE)


table_15 <- tableby(gpa_grp ~ ERQ_reap + ERQ_sup + GSE_sum + MEMS_sum + SSSI_avg, data = data_vis)
summary(table_15, title = "Latent By GPA", text = TRUE)


table_16 <- tableby(gpa_change_grp ~ ERQ_reap + ERQ_sup + GSE_sum + MEMS_sum + SSSI_avg, data = data_vis)
summary(table_16, title = "Latent By GPA(change)", text = TRUE)


#-------------------------------------------------------
#Part 2, specifics MEMS and SLASIA
table_21 <- tableby(age_grp ~ SCOFF_binge + MEMS1 + MEMS2 + MEMS3 + MEMS4 + SLASIA1, data = data_vis)
summary(table_21, title = "spec By Age", text = TRUE)


table_22 <- tableby(gender_grp ~ SCOFF_binge + MEMS1 + MEMS2 + MEMS3 + MEMS4 + SLASIA1, data = data_vis)
summary(table_22, title = "spec By Gender", text = TRUE)


table_23 <- tableby(degree_grp ~ SCOFF_binge + MEMS1 + MEMS2 + MEMS3 + MEMS4 + SLASIA1, data = data_vis)
summary(table_23, title = "spec By Degree", text = TRUE)


table_24 <- tableby(religion_grp ~ SCOFF_binge + MEMS1 + MEMS2 + MEMS3 + MEMS4 + SLASIA1, data = data_vis)
summary(table_24, title = "spec By Religion", text = TRUE)


table_25 <- tableby(gpa_grp ~ SCOFF_binge + MEMS1 + MEMS2 + MEMS3 + MEMS4 + SLASIA1, data = data_vis)
summary(table_25, title = "spec By GPA", text = TRUE)


table_26 <- tableby(gpa_change_grp ~ SCOFF_binge + MEMS1 + MEMS2 + MEMS3 + MEMS4 + SLASIA1, data = data_vis)
summary(table_26, title = "Latent By GPA(change)", text = TRUE)

```



